packages:
  - "packages/*"

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  skia-canvas: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - skia-canvas
  - unrs-resolver

patchedDependencies:
  vaul@1.1.2: patches/vaul@1.1.2.patch
