#!/usr/bin/env sh
# Creates local-dev env files for the docker compose stack. Never overwrites an existing file.
set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"

secret() { openssl rand -hex "$1"; }

render_secret=""

if [ -e .env.local ]; then
  echo ".env.local exists, leaving it alone"
else
  render_secret=$(secret 32)
  cat > .env.local <<EOF
# Generated by \`make setup\` for the local docker compose stack (docker-compose.yml).

NEXT_PUBLIC_SITE_URL=http://localhost:3000
BETTER_AUTH_URL=http://localhost:3000
BETTER_AUTH_SECRET=$(secret 32)
NEXT_PUBLIC_ACCOUNT_SIGNUP_TYPE=enabled

POSTGRES_URL=postgres://tomomai:tomomai@localhost:${POSTGRES_PORT:-5432}/tomomai
REDIS_URL=redis://localhost:${REDIS_PORT:-6379}

# RustFS stands in for R2.
R2_ENDPOINT=http://localhost:${S3_PORT:-9000}
R2_FORCE_PATH_STYLE=true
R2_ACCESS_KEY_ID=tomomai
R2_SECRET_ACCESS_KEY=tomomai-dev-secret
R2_BUCKET=tomomai
NEXT_PUBLIC_R2_URL=http://localhost:${S3_PORT:-9000}/tomomai
NEXT_PUBLIC_R2_URL_CN=http://localhost:${S3_PORT:-9000}/tomomai

TOKEN_SECRET=$(secret 32)
MAIMAI_TOTP_SECRET=$(secret 20)
CRON_SECRET=$(secret 16)
ADMIN_UPDATE_TOKEN=$(secret 16)

# Run apps/render with \`pnpm render:dev\`.
RENDER_TOKEN_SECRET=$render_secret
RENDER_PUBLIC_URL=http://localhost:8080
RENDER_INTERNAL_URL=http://localhost:8080

# Optional: fill in to test real OAuth. The dev-only anonymous sign-in works without them.
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
TWITTER_CLIENT_ID=
TWITTER_CLIENT_SECRET=
EOF
  echo "created .env.local"
fi

if [ -e apps/main/.env.local ] || [ -L apps/main/.env.local ]; then
  echo "apps/main/.env.local exists, leaving it alone"
else
  ln -s ../../.env.local apps/main/.env.local
  echo "linked apps/main/.env.local -> ../../.env.local"
fi

if [ -e apps/render/.env.local ]; then
  echo "apps/render/.env.local exists, leaving it alone"
  if [ -n "$render_secret" ]; then
    echo "  warning: set RENDER_TOKEN_SECRET in apps/render/.env.local to match .env.local"
  fi
else
  root_existed=false
  if [ -z "$render_secret" ]; then
    root_existed=true
    render_secret=$(secret 32)
  fi
  sed \
    -e "s|^RENDER_TOKEN_SECRET=.*|RENDER_TOKEN_SECRET=$render_secret|" \
    -e "s|^# CATALOG_URL=.*|CATALOG_URL=http://localhost:3000|" \
    -e "s|^NEXT_PUBLIC_R2_URL=.*|NEXT_PUBLIC_R2_URL=http://localhost:${S3_PORT:-9000}/tomomai|" \
    -e "s|^NEXT_PUBLIC_R2_URL_CN=.*|NEXT_PUBLIC_R2_URL_CN=http://localhost:${S3_PORT:-9000}/tomomai|" \
    apps/render/.env.example > apps/render/.env.local
  echo "created apps/render/.env.local"
  if [ "$root_existed" = true ]; then
    echo "  warning: set RENDER_TOKEN_SECRET in .env.local to match apps/render/.env.local"
  fi
fi
