CREATE TABLE "parent_song" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parent_song_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"publicId" varchar(21) NOT NULL,
	"songName" text NOT NULL,
	"artist" text NOT NULL,
	"genre" text NOT NULL,
	"cover" text NOT NULL,
	"bpm" smallint,
	"type" chart_type NOT NULL,
	"difficulty" "difficulty" NOT NULL,
	"disambiguator" smallint DEFAULT 0 NOT NULL,
	CONSTRAINT "parent_song_publicId_unique" UNIQUE("publicId"),
	CONSTRAINT "parent_song_name_type_difficulty_disambiguator_unique" UNIQUE("songName","type","difficulty","disambiguator")
);
--> statement-breakpoint
ALTER TABLE "songs" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "tour_event_steps" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "tour_events" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "songs" ADD COLUMN "parentId" bigint;--> statement-breakpoint
CREATE INDEX "parent_song_publicid_idx" ON "parent_song" USING btree ("publicId");--> statement-breakpoint
CREATE INDEX "parent_song_songname_type_idx" ON "parent_song" USING btree ("songName","type");--> statement-breakpoint
ALTER TABLE "songs" ADD CONSTRAINT "songs_parentId_parent_song_id_fk" FOREIGN KEY ("parentId") REFERENCES "public"."parent_song"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "songs_parentid_idx" ON "songs" USING btree ("parentId");