CREATE TABLE "catalog_state" (
	"id" integer PRIMARY KEY NOT NULL,
	"sequence" bigint NOT NULL,
	"schemaVersion" integer NOT NULL,
	"sha256" text NOT NULL,
	"sourceUrl" text NOT NULL,
	"syncedAt" timestamp (0) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "parent_song" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "songs" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "tour_event_steps" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "tour_events" ALTER COLUMN "id" SET GENERATED BY DEFAULT;