CREATE TYPE "public"."chart_type" AS ENUM('std', 'dx');--> statement-breakpoint
CREATE TYPE "public"."difficulty" AS ENUM('basic', 'advanced', 'expert', 'master', 'remaster', 'utage');--> statement-breakpoint
CREATE TYPE "public"."level" AS ENUM('1', '1+', '2', '2+', '3', '3+', '4', '4+', '5', '5+', '6', '6+', '7', '7+', '8', '8+', '9', '9+', '10', '10+', '11', '11+', '12', '12+', '13', '13+', '14', '14+', '15', '15+', '16', '16+');--> statement-breakpoint
CREATE TYPE "public"."region" AS ENUM('intl', 'jp', 'cn');--> statement-breakpoint
CREATE TABLE "catalog_releases" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "catalog_releases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sequence" integer NOT NULL,
	"schemaVersion" smallint NOT NULL,
	"sha256" varchar(64) NOT NULL,
	"url" text NOT NULL,
	"parentCount" integer NOT NULL,
	"songCount" integer NOT NULL,
	"tourEventCount" integer NOT NULL,
	"createdAt" timestamp (0) DEFAULT now() NOT NULL,
	CONSTRAINT "catalog_releases_sequence_unique" UNIQUE("sequence")
);
--> statement-breakpoint
CREATE TABLE "parent_song" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parent_song_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"publicId" varchar(21) NOT NULL,
	"songName" text NOT NULL,
	"artist" text NOT NULL,
	"genre" text NOT NULL,
	"cover" text NOT NULL,
	"bpm" smallint,
	"type" chart_type NOT NULL,
	"difficulty" "difficulty" NOT NULL,
	"disambiguator" smallint DEFAULT 0 NOT NULL,
	CONSTRAINT "parent_song_publicId_unique" UNIQUE("publicId"),
	CONSTRAINT "parent_song_name_type_difficulty_disambiguator_unique" UNIQUE("songName","type","difficulty","disambiguator")
);
--> statement-breakpoint
CREATE TABLE "songs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "songs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"parentId" bigint NOT NULL,
	"level" "level" NOT NULL,
	"levelPrecise" smallint NOT NULL,
	"region" "region" NOT NULL,
	"gameVersion" smallint NOT NULL,
	"addedVersion" smallint NOT NULL,
	"noteDesigner" text,
	"tapCount" smallint,
	"holdCount" smallint,
	"slideCount" smallint,
	"touchCount" smallint,
	"breakCount" smallint,
	CONSTRAINT "songs_parent_region_version_unique" UNIQUE("parentId","region","gameVersion")
);
--> statement-breakpoint
CREATE TABLE "tour_event_steps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tour_event_steps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"eventId" integer NOT NULL,
	"distance" integer NOT NULL,
	"type" text NOT NULL,
	"reward" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tour_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tour_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"periods" jsonb NOT NULL,
	"createdAt" timestamp (0) DEFAULT now() NOT NULL,
	"updatedAt" timestamp (0) DEFAULT now() NOT NULL,
	CONSTRAINT "tour_events_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "songs" ADD CONSTRAINT "songs_parentId_parent_song_id_fk" FOREIGN KEY ("parentId") REFERENCES "public"."parent_song"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tour_event_steps" ADD CONSTRAINT "tour_event_steps_eventId_tour_events_id_fk" FOREIGN KEY ("eventId") REFERENCES "public"."tour_events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "parent_song_publicid_idx" ON "parent_song" USING btree ("publicId");--> statement-breakpoint
CREATE INDEX "parent_song_songname_type_idx" ON "parent_song" USING btree ("songName","type");--> statement-breakpoint
CREATE INDEX "songs_parentid_idx" ON "songs" USING btree ("parentId");--> statement-breakpoint
CREATE INDEX "songs_region_gameversion_idx" ON "songs" USING btree ("region","gameVersion");--> statement-breakpoint
CREATE INDEX "tour_event_steps_eventid_idx" ON "tour_event_steps" USING btree ("eventId");